name: pipeline
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-app:
    name: Build - App
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build app and run unit tests
        run: |
          dotnet restore web-app/web-app.csproj
          dotnet restore unit-tests/unit-tests.csproj
          dotnet build web-app/web-app.csproj --configuration Release
          dotnet build unit-tests/unit-tests.csproj --configuration Release
          dotnet test unit-tests/unit-tests.csproj

      - name: Create Azure container registry using Bicep
        run: >
          az deployment group create \
            --resource-group '${{ env.APPNAME }}-ACR-rg' \
            --template-file iac/registry.bicep \
            --parameters registry='${{ env.REGISTRYNAME }}'

      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRYNAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker Build & Push to ACR
        run: |
          docker login ${{ env.REGISTRYNAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
          docker build "$GITHUB_WORKSPACE" -f  "Dockerfile" -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }} 
          docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }}

  build-database:
    name: Build - Database
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3.1.0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Use MSBuild to build db project
        run: MSBuild.exe database/database.sqlproj

      - name: Copy dacpac before artifact Upload
        run: Copy-Item "database/bin/Debug/database.dacpac" -Destination "database.dacpac"

      - name: Upload dacpac as artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: dacpac
          path: database.dacpac

  build-iac:
    name: Build - Infrastructure
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep templates to ensure transpilation, linting, and preflight are successful
        working-directory: iac
        env:
          ENVIRONMENTNAME: dev
          DEVENV: true
        run: |
          az deployment sub validate \
            --name 'spacegamedeploy-${{ env.ENVIRONMENTNAME }}' \
            --location 'WestUS' \
            --template-file main.bicep \
            --parameters appName='spacegamevnext' \
                         environmentName=${{ env.ENVIRONMENTNAME }} \
                         registryName='marcusfellingspacegamevnextacr' \
                         tag='${{ github.sha }}' \
                         dbUserName='${{ secrets.DBUSERNAME }}' \
                         dbPassword='${{ secrets.DBPASSWORD }}' \
                         devEnv='${{ env.DEVENV }}'

  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "dev"
      devenv: true
      envurl: https://spacegamevnext-dev-${{ github.RUN_ID }}.azurewebsites.net
    concurrency:
      group: dev
      cancel-in-progress: true
    needs: [build-app, build-database, build-iac]

  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "test"
      devenv: false
      envurl: https://spacegamevnext-test.azurewebsites.net
    concurrency:
      group: test
      cancel-in-progress: true
    needs: [deploy-dev]

  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.27.0-focal
    environment:
      name: test
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    concurrency:
      group: test
      cancel-in-progress: true
    env:
      ENVIRONMENTNAME: test-e2e
      BASEURL: https://spacegamevnext-test.azurewebsites.net # Playwright tests use this env var
    defaults:
      run:
        working-directory: e2e-tests
    needs: [deploy-test]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright Tests
        continue-on-error: false
        run: |
          HOME=/root npx playwright test

      - name: Create test summary
        uses: test-summary/action@v2.0
        if: always()
        with:
          paths: e2e-tests/results/junit.xml

      - uses: actions/upload-artifact@v3.1.1
        name: Upload HTML report
        if: always()
        with:
          name: e2e-tests-report
          path: e2e-tests/results/html

  test-load:
    name: Run Load Tests
    runs-on: ubuntu-22.04
    environment:
      name: test-load
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    concurrency:
      group: test-load
      cancel-in-progress: true
    env:
      ENVIRONMENTNAME: test
    needs: [deploy-test, test-e2e]
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Azure Load Testing - Home Page Test"
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: "load-tests/home-page.yaml"
          loadTestResource: ${{ env.APPNAME }}-loadtest
          resourceGroup: ${{ env.APPNAME }}-loadtest-rg
          env: |
            [
                {
                "name": "HOMEPAGE_URL",
                "value": "spacegamevnext-test.azurewebsites.net"
                }
            ]

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
      devenv: true
      envurl: https://spacegamevnext-prod.azurewebsites.net
    concurrency:
      group: prod
      cancel-in-progress: true
    needs: [deploy-test, test-load, test-e2e]
