name: pipeline
on: [workflow_dispatch, push]
env:
  APPNAME: spacegamevnext # Name of app. Used for prefix in resource group, service plan, app service, container images, sql server and database.
  REGISTRYSKU: 'Standard'
  REGISTRYNAME: 'marcusfellingspacegamevnextacr' # Registry that is shared across environments
  LOCATION: 'WestUS' # Region for all Azure resources
  SKU: 'S2' # Default Sku for app services 

jobs:
  buildApp:
    name: Build - App
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@master

    - name: Azure authentication
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build app and run unit tests 
      run: | 
            dotnet restore WebApp/WebApp.csproj
            dotnet restore UnitTests/UnitTests.csproj
            dotnet build WebApp/WebApp.csproj --configuration Release
            dotnet build UnitTests/UnitTests.csproj --configuration Release
            dotnet test UnitTests/UnitTests.csproj --verbosity normal

    - name: Create Azure container registry using Bicep
      run: >
        az deployment group create \
          --resource-group '${{ env.APPNAME }}-ACR-rg' \
          --template-file IaC/registry.bicep \
          --parameters registry='${{ env.REGISTRYNAME }}' \
                       registrySku='${{ env.REGISTRYSKU }}'        

    - name: Fetch ACR credentials
      id: acrCredentials
      continue-on-error: false
      run: |
          echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username`"
          echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"
          echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"

    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRYNAME }}.azurecr.io
        username: ${{ steps.acrCredentials.outputs.acr_username }}
        password: ${{ steps.acrCredentials.outputs.acr_password }}

    - name: Docker Build & Push to ACR
      run: |
        docker login ${{ env.REGISTRYNAME }}.azurecr.io --username ${{ steps.acrCredentials.outputs.acr_username }} --password ${{ steps.acrCredentials.outputs.acr_password }}
        docker build "$GITHUB_WORKSPACE" -f  "Dockerfile" -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }} 
        docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }}   

  buildDatabase:
    name: Build - Database
    runs-on: windows-latest  
    steps:
    - uses: actions/checkout@master
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Use MSBuild to build db project
      run: MSBuild.exe Database/Database.sqlproj
    
    - name: Copy dacpac before artifact Upload
      run: Copy-Item "Database/bin/Debug/Database.dacpac" -Destination "Database.dacpac"

    - name: Upload dacpac as artifact    
      uses: actions/upload-artifact@v2
      with:
        name: dacpac
        path: Database.dacpac

  buildIaC:
    name: Build - Infrastructure
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@master
    - name: Run Bicep build to ensure transpilation is successful before deployment
      run: | 
        az bicep build --files IaC/main.bicep    

  deployDev:
    name: Deploy to Dev
    environment: 
      name: dev
      url: https://${{ env.APPNAME }}-${{ env.BRANCH_NAME }}.azurewebsites.net
    env:
      ENVIRONMENTNAME: dev
      DEVENV: true
    needs: [buildApp, buildDatabase, buildIaC]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract branch name to append to app name
      run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: Preview infrastructure changes
      run: >
        az deployment sub what-if \
          --name 'spacegamedeploy-${{ env.ENVIRONMENTNAME }}' \
          --location '${{ env.LOCATION }}' \
          --template-file IaC/main.bicep \
          --parameters appName='${{ env.APPNAME }}' \
                       environmentName=${{ env.ENVIRONMENTNAME }} \
                       branchName='-${{ env.BRANCH_NAME }}' \
                       appSku='${{ env.SKU }}' \
                       registryName='${{ env.REGISTRYNAME }}' \
                       tag='${{ github.sha }}' \
                       registrySku='${{ env.REGISTRYSKU }}' \
                       dbUserName='${{ secrets.DBUSERNAME }}' \
                       dbPassword='${{ secrets.DBPASSWORD }}' \
                       devEnv='${{ env.DEVENV }}'

    - name: Deploy infrastructure
      run: >
        az deployment sub create \
          --name 'spacegamedeploy-${{ env.ENVIRONMENTNAME }}' \
          --location '${{ env.LOCATION }}' \
          --template-file IaC/main.bicep \
          --parameters appName='${{ env.APPNAME }}' \
                       environmentName=${{ env.ENVIRONMENTNAME }} \
                       branchName='-${{ env.BRANCH_NAME }}' \
                       appSku='${{ env.SKU }}' \
                       registryName='${{ env.REGISTRYNAME }}' \
                       tag='${{ github.sha }}' \
                       registrySku='${{ env.REGISTRYSKU }}' \
                       dbUserName='${{ secrets.DBUSERNAME }}' \
                       dbPassword='${{ secrets.DBPASSWORD }}' \
                       devEnv='${{ env.DEVENV }}'

    - uses: actions/download-artifact@v2
      name: download dacpac from build
      with:
        name: dacpac

    - name: Deploy Database using dacpac
      uses: docker://markhobson/sqlpackage:latest # Use container with sqlpackage.exe
      with:
        args: /SourceFile:"Database.dacpac" /Action:Publish /TargetServerName:"${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}-sql.database.windows.net" /TargetDatabaseName:"${{ env.APPNAME }}database" /TargetUser:"${{ secrets.DBUSERNAME }}" /TargetPassword:"${{ secrets.DBPASSWORD }}"

    - name: Get ACR credentials
      id: getACRCred
      run: |
           echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username | xargs`"
           echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`"
           echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`" 

    - name: 'Deploy to Azure Web App for Containers'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: '${{ env.APPNAME }}-${{ env.BRANCH_NAME }}'
        images: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }}

  deployTest:
    name: Deploy to Test
    runs-on: ubuntu-20.04
    environment: 
      name: test
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    env:
      ENVIRONMENTNAME: test
      DEVENV: false
    needs: [deployDev]
    steps:
    - uses: actions/checkout@master

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infrastructure
      run: >
        az deployment sub create \
          --name 'spacegamedeploy-${{ env.ENVIRONMENTNAME }}' \
          --location '${{ env.LOCATION }}' \
          --template-file IaC/main.bicep \
          --parameters appName='${{ env.APPNAME }}' \
                       environmentName=${{ env.ENVIRONMENTNAME }} \
                       appSku='${{ env.SKU }}' \
                       registryName='${{ env.REGISTRYNAME }}' \
                       tag='${{ github.sha }}' \
                       registrySku='${{ env.REGISTRYSKU }}' \
                       dbUserName='${{ secrets.DBUSERNAME }}' \
                       dbPassword='${{ secrets.DBPASSWORD }}' \
                       devEnv='${{ env.DEVENV }}'

    - uses: actions/download-artifact@v2
      name: Download dacpac from build
      with:
        name: dacpac

    - name: Deploy Database using dacpac
      uses: docker://markhobson/sqlpackage:latest # Use container with sqlpackage.exe
      with:
        args: /SourceFile:"Database.dacpac" /Action:Publish /TargetServerName:"${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}-sql.database.windows.net" /TargetDatabaseName:"${{ env.APPNAME }}database" /TargetUser:"${{ secrets.DBUSERNAME }}" /TargetPassword:"${{ secrets.DBPASSWORD }}"

    - name: Get ACR credentials
      id: getACRCred
      run: |
           echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username | xargs`"
           echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`"
           echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`" 

    - name: 'Deploy to Azure Web App for Containers slot'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}'
        slot-name: 'swap'
        images: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }} 

    - name: Swap slots for no downtime deploy
      run: |
        az webapp deployment slot swap -g '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}-rg' -n '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}' --slot 'swap' --target-slot 'production'

  testFunctional:
    name: Run functional tests
    runs-on: windows-latest
    environment: 
      name: test
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    env:
      SITE_URL: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net # Referenced by Selenium test
    needs: [deployTest]
    steps:
    - uses: actions/checkout@master
    - name: Run functional tests
      continue-on-error: false
      run: dotnet test FunctionalTests/FunctionalTests.csproj

  testLoad:
    name: Run load tests
    runs-on: ubuntu-20.04
    container: justb4/jmeter:5.3 # Use container with JMeter installed
    environment: 
      name: test
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    env:
      SITE_URL: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net # Used by JMeter tests
    needs: deployTest
    steps:
    - uses: actions/checkout@master
    - name: Run load tests
      run: | 
        cd LoadTests        
        ${JMETER_HOME}/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=${{ env.SITE_URL }}

  deployProd:
    name: Deploy to Prod
    runs-on: ubuntu-20.04
    environment: 
      name: prod
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    env:
      ENVIRONMENTNAME: prod
      DEVENV: false
    needs: [testLoad, testFunctional]
    steps:
    - uses: actions/checkout@master
        
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infrastructure
      run: >
        az deployment sub create \
          --name 'spacegamedeploy-${{ env.ENVIRONMENTNAME }}' \
          --location '${{ env.LOCATION }}' \
          --template-file IaC/main.bicep \
          --parameters appName='${{ env.APPNAME }}' \
                       environmentName=${{ env.ENVIRONMENTNAME }} \
                       appSku='${{ env.SKU }}' \
                       registryName='${{ env.REGISTRYNAME }}' \
                       tag='${{ github.sha }}' \
                       registrySku='${{ env.REGISTRYSKU }}' \
                       dbUserName='${{ secrets.DBUSERNAME }}' \
                       dbPassword='${{ secrets.DBPASSWORD }}' \
                       devEnv='${{ env.DEVENV }}'     

    - uses: actions/download-artifact@v2
      name: Download dacpac from build
      with:
        name: dacpac

    - name: Deploy Database using dacpac
      uses: docker://markhobson/sqlpackage:latest # Use container with sqlpackage.exe
      with:
        args: /SourceFile:"Database.dacpac" /Action:Publish /TargetServerName:"${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}-sql.database.windows.net" /TargetDatabaseName:"${{ env.APPNAME }}database" /TargetUser:"${{ secrets.DBUSERNAME }}" /TargetPassword:"${{ secrets.DBPASSWORD }}"

    - name: Get ACR credentials
      id: getACRCred
      run: |
           echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username | xargs`"
           echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`"
           echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`" 

    - name: 'Deploy to Azure Web App for Containers slot'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}'
        slot-name: 'swap'
        images: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.APPNAME }}:${{ github.sha }} 

    - name: Swap slots for no downtime deploy
      run: |
        az webapp deployment slot swap -g '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}-rg' -n '${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}' --slot 'swap' --target-slot 'production'      
