name: pipeline
on: [workflow_dispatch, push]
env:
  APPNAME: spacegamevnext # Name of app. Used for prefix in resource group, service plan, app service, container images, sql server and database.
  REGISTRYNAME: "marcusfellingspacegamevnextacr" # Registry that is shared across environments
  LOCATION: "WestUS" # Region for all Azure resources

jobs:

  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/playwright:v1.21.0-focal
    environment:
      name: test
      url: https://${{ env.APPNAME }}-${{ env.ENVIRONMENTNAME }}.azurewebsites.net
    env:
      ENVIRONMENTNAME: test-e2e
      SITE_URL: https://spacegamevnext-test.azurewebsites.net # Playwright tests use this env var

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright Tests
        continue-on-error: false
        run: |
          HOME=/root npx playwright test --config e2e-tests/playwright.config.ts

      - name: Create test summary
        uses: test-summary/action@dist
        if: always()
        with:
          paths: test-results/junit.xml

      - uses: actions/upload-artifact@v2
        name: Upload HTML report
        if: always()
        with:
          name: e2e-tests-report
          path: e2e-tests/test-results/html

 